'use strict';
const CFG=require('./config');const db=require('./db');const {normUsername}=require('./utils');
class BoundedMap extends Map{constructor(max,onEvict){super();this.maxSize=max;this.onEvict=onEvict}set(k,v){if(!this.has(k)&&this.size>=this.maxSize){const key=this.keys().next().value,val=this.get(key);super.delete(key);try{this.onEvict?.(val,key)}catch(e){console.error('[BoundedMap]',e.message)}}return super.set(k,v)}}
let destroyBotRef=()=>{};let notifyRef=null;const bindDestroyBot=f=>{destroyBotRef=f};const bindNotifier=f=>{notifyRef=f};
const mcBots=new BoundedMap(CFG.MAX_BOTS_GLOBAL,info=>{destroyBotRef(info);db.removeBot(info.id);notifyRef?.(info.chatId,`⚠️ <b>${info.name}</b> was removed — server bot capacity was reached.`)});const forwardMap=db.loadAllForwards();const chatStates=new Map();
const setChatState=(id,state)=>chatStates.set(id,{...state,expiresAt:Date.now()+CFG.CHAT_STATE_TTL_MS});const getChatState=id=>{const s=chatStates.get(id);if(!s)return null;if(s.expiresAt<Date.now()){chatStates.delete(id);return null}return s};const clearChatState=id=>chatStates.delete(id);const sweepChatStates=()=>{for(const [k,v] of chatStates)if(v.expiresAt<Date.now())chatStates.delete(k)};setInterval(sweepChatStates,CFG.CHAT_STATE_SWEEP_MS).unref();
let shuttingDown=false;const getBot=id=>mcBots.get(String(id));const currentUserOwns=(i,u,c,n)=>i.userId!=null&&u!=null?String(i.userId)===String(u):Boolean(u&&n&&i.ownerUsername&&normUsername(i.ownerUsername)===normUsername(n));const ownedBots=(u,c,n)=>[...mcBots.values()].filter(i=>currentUserOwns(i,u,c,n));
const claimLegacyOwnership=(i,u,n)=>{if(!i||i.userId!=null||!u||!n||normUsername(i.ownerUsername)!==normUsername(n))return;i.userId=u;const old='username:'+normUsername(i.ownerUsername),groups=forwardMap.get(old);if(groups?.size){if(!forwardMap.has(String(u)))forwardMap.set(String(u),new Set());for(const x of groups)forwardMap.get(String(u)).add(x);forwardMap.delete(old);db.renameForwardKey(old,String(u))}db.saveBot(i)};
const canAddBot=u=>mcBots.size>=CFG.MAX_BOTS_GLOBAL?{ok:false,reason:`Server is at capacity (${CFG.MAX_BOTS_GLOBAL} bots). Try again later.`}:[...mcBots.values()].filter(i=>i.userId!=null&&String(i.userId)===String(u)).length>=CFG.MAX_BOTS_PER_USER?{ok:false,reason:`You've reached your limit of ${CFG.MAX_BOTS_PER_USER} bots. Remove one first.`}:{ok:true};const canAddForward=k=>(forwardMap.get(k)?.size||0)>=CFG.MAX_FORWARDS_PER_USER?{ok:false,reason:`You've reached your limit of ${CFG.MAX_FORWARDS_PER_USER} forwarding chats.`}:{ok:true};module.exports={BoundedMap,mcBots,forwardMap,chatStates,setChatState,getChatState,clearChatState,sweepChatStates,isShuttingDown:()=>shuttingDown,setShuttingDown:v=>{shuttingDown=!!v},getBot,currentUserOwns,ownedBots,claimLegacyOwnership,canAddBot,canAddForward,bindDestroyBot,bindNotifier};
